# CodeDeploy 버전
version: 0.0
os: linux
files:
  # CodeDeploy에서 전달해 준 파일 중 destination으로 이동시킬 대상 지정
  - source: /
    destination: /home/ec2-user/app/step2/zip/ # source에서 지정된 파일을 받을 위치
    overwrite: yes

# CodeDeploy에서 EC2 서버로 넘겨준 파일들을 모두 ec2-user 권한을 갖도록 함
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

# CodeDeploy 배포 단계에서 실행할 명령어를 지정
hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 60
      runas: ec2-user